#!/bin/bash

ln -sf /opt/atol-websocket-kkm /opt/atol

apt-get -y purge modemmanager
apt-get install python-serial

cp service /etc/systemd/system/atol-kkm.service

systemctl daemon-reload
systemctl enable atol-kkm
systemctl start atol-kkm

systemctl -l status atol-kkm
